### ISSUE TITLE
TypeError: Invalid comparator: ember-cli/loader.js

### ISSUE THREAD

**Issue by alexmiddeleer** [kellyselden/ember-cli-update#142]
Running on a Mac, the command fails with the following exception with v0.7.1. I have tried `--to "2.12"` and `--to "2.12.0"`. This project is an addon.

```
TypeError: Invalid comparator: ember-cli/loader.js
    at Comparator.parse (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:662:8)
    at /Users/alex/.config/yarn/global/node_modules/semver/semver.js:828:12
    at Array.map (native)
    at Range.parseRange (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:827:13)
    at Range.<anonymous> (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:769:17)
    at Array.map (native)
    at new Range (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:768:40)
    at minVersion (/Users/alex/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:14:11)
    at /Users/alex/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:57:19
```

Full output:
```
Alexs-MacBook-Pro-3:rp-common alex$ DEBUG=ember-cli-update,git-diff-apply ember-cli-update --to "2.12"
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
  ember-cli-update   "0.0.1",
  ember-cli-update   "0.0.2",
  ember-cli-update   "0.0.3",
  ember-cli-update   "0.0.4",
  ember-cli-update   "0.0.5",
  ember-cli-update   "0.0.6",
  ember-cli-update   "0.0.7",
  ember-cli-update   "0.0.8",
  ember-cli-update   "0.0.9",
  ember-cli-update   "0.0.10",
  ember-cli-update   "0.0.11",
  ember-cli-update   "0.0.12",
  ember-cli-update   "0.0.13",
  ember-cli-update   "0.0.14",
  ember-cli-update   "0.0.15",
  ember-cli-update   "0.0.16",
  ember-cli-update   "0.0.18",
  ember-cli-update   "0.0.19",
  ember-cli-update   "0.0.20",
  ember-cli-update   "0.0.21",
  ember-cli-update   "0.0.22",
  ember-cli-update   "0.0.23",
  ember-cli-update   "0.0.24",
  ember-cli-update   "0.0.25",
  ember-cli-update   "0.0.27",
  ember-cli-update   "0.0.28",
  ember-cli-update   "0.0.29",
  ember-cli-update   "0.0.32",
  ember-cli-update   "0.0.33",
  ember-cli-update   "0.0.34",
  ember-cli-update   "0.0.35",
  ember-cli-update   "0.0.36",
  ember-cli-update   "0.0.37",
  ember-cli-update   "0.0.38",
  ember-cli-update   "0.0.39",
  ember-cli-update   "0.0.40",
  ember-cli-update   "0.0.41",
  ember-cli-update   "0.0.42",
  ember-cli-update   "0.0.43",
  ember-cli-update   "0.0.44",
  ember-cli-update   "0.0.45",
  ember-cli-update   "0.0.46",
  ember-cli-update   "0.0.47",
  ember-cli-update   "0.1.0",
  ember-cli-update   "0.1.1",
  ember-cli-update   "0.1.2",
  ember-cli-update   "0.1.3",
  ember-cli-update   "0.1.4",
  ember-cli-update   "0.1.5",
  ember-cli-update   "0.1.6",
  ember-cli-update   "0.1.7",
  ember-cli-update   "0.1.8",
  ember-cli-update   "0.1.9",
  ember-cli-update   "0.1.10",
  ember-cli-update   "0.1.11",
  ember-cli-update   "0.1.12",
  ember-cli-update   "0.1.13",
  ember-cli-update   "0.1.14",
  ember-cli-update   "0.1.15",
  ember-cli-update   "0.2.0-beta.1",
  ember-cli-update   "0.2.0",
  ember-cli-update   "0.2.1",
  ember-cli-update   "0.2.2",
  ember-cli-update   "0.2.3",
  ember-cli-update   "0.2.4",
  ember-cli-update   "0.2.5",
  ember-cli-update   "0.2.6",
  ember-cli-update   "0.2.7",
  ember-cli-update   "1.13.0",
  ember-cli-update   "1.13.1",
  ember-cli-update   "1.13.5",
  ember-cli-update   "1.13.6",
  ember-cli-update   "1.13.7",
  ember-cli-update   "1.13.8",
  ember-cli-update   "1.13.9",
  ember-cli-update   "1.13.10",
  ember-cli-update   "1.13.11",
  ember-cli-update   "1.13.12",
  ember-cli-update   "1.13.13",
  ember-cli-update   "1.13.14",
  ember-cli-update   "1.13.15",
  ember-cli-update   "2.2.0-beta.1",
  ember-cli-update   "2.2.0-beta.2",
  ember-cli-update   "2.2.0-beta.3",
  ember-cli-update   "2.2.0-beta.4",
  ember-cli-update   "2.2.0-beta.5",
  ember-cli-update   "2.2.0-beta.6",
  ember-cli-update   "2.3.0-beta.1",
  ember-cli-update   "2.3.0-beta.2",
  ember-cli-update   "2.3.0",
  ember-cli-update   "2.4.0",
  ember-cli-update   "2.4.1",
  ember-cli-update   "2.4.2",
  ember-cli-update   "2.4.3",
  ember-cli-update   "2.5.0",
  ember-cli-update   "2.5.1",
  ember-cli-update   "2.6.0-beta.1",
  ember-cli-update   "2.6.0-beta.2",
  ember-cli-update   "2.6.0-beta.3",
  ember-cli-update   "2.6.0",
  ember-cli-update   "2.6.1",
  ember-cli-update   "2.6.2",
  ember-cli-update   "2.6.3",
  ember-cli-update   "2.7.0-beta.1",
  ember-cli-update   "2.7.0-beta.2",
  ember-cli-update   "2.7.0-beta.3",
  ember-cli-update   "2.7.0-beta.4",
  ember-cli-update   "2.7.0-beta.5",
  ember-cli-update   "2.7.0-beta.6",
  ember-cli-update   "2.7.0",
  ember-cli-update   "2.8.0-beta.1",
  ember-cli-update   "2.8.0-beta.2",
  ember-cli-update   "2.8.0-beta.3",
  ember-cli-update   "2.8.0",
  ember-cli-update   "2.9.0-beta.1",
  ember-cli-update   "2.9.0-beta.2",
  ember-cli-update   "2.9.0",
  ember-cli-update   "2.9.1",
  ember-cli-update   "2.10.0-beta.1",
  ember-cli-update   "2.10.0-beta.2",
  ember-cli-update   "2.10.0",
  ember-cli-update   "2.10.1",
  ember-cli-update   "2.11.0-beta.1",
  ember-cli-update   "2.11.0-beta.2",
  ember-cli-update   "2.11.0",
  ember-cli-update   "2.11.1",
  ember-cli-update   "2.12.0-beta.1",
  ember-cli-update   "2.12.0-beta.2",
  ember-cli-update   "2.12.0",
  ember-cli-update   "2.12.1",
  ember-cli-update   "2.12.2",
  ember-cli-update   "2.12.3",
  ember-cli-update   "2.13.0-beta.1",
  ember-cli-update   "2.13.0-beta.2",
  ember-cli-update   "2.13.0-beta.3",
  ember-cli-update   "2.13.0-beta.4",
  ember-cli-update   "2.13.0",
  ember-cli-update   "2.13.1",
  ember-cli-update   "2.13.2",
  ember-cli-update   "2.13.3",
  ember-cli-update   "2.14.0-beta.1",
  ember-cli-update   "2.14.0-beta.2",
  ember-cli-update   "2.14.0",
  ember-cli-update   "2.14.1",
  ember-cli-update   "2.14.2",
  ember-cli-update   "2.15.0-beta.1",
  ember-cli-update   "2.15.0-beta.2",
  ember-cli-update   "2.15.0",
  ember-cli-update   "2.15.1",
  ember-cli-update   "2.16.0-beta.1"
  ember-cli-update ]
  ember-cli-update  +719ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  +26ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-addon-output /var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git +2ms
Cloning into bare repository '/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git'...
  git-diff-apply  +3s
  git-diff-apply git symbolic-ref --short HEAD +0ms
  git-diff-apply 3181-test
  git-diff-apply  +11ms
  git-diff-apply git checkout --orphan 11954e60-a215-11e7-99d9-f16f7bd616cd +0ms
Switched to a new branch '11954e60-a215-11e7-99d9-f16f7bd616cd'
  git-diff-apply  +25ms
  git-diff-apply git reset --hard +0ms
  git-diff-apply  +65ms
  git-diff-apply git --git-dir="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git" rev-parse v2.11.1 +1ms
  git-diff-apply 4baef6cb129249d665dab414bd3535f1ca6bc037
  git-diff-apply  +11ms
  git-diff-apply git --git-dir="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git" --work-tree="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN" checkout 4baef6cb129249d665dab414bd3535f1ca6bc037 +0ms
Note: checking out '4baef6cb129249d665dab414bd3535f1ca6bc037'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4baef6c... 2.11.1
  git-diff-apply  +18ms
  git-diff-apply copy /var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN /Users/alex/proj/rp-common +0ms
  git-diff-apply [ '.bowerrc',
  git-diff-apply   '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.jshintrc',
  git-diff-apply   '.npmignore',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'LICENSE.md',
  git-diff-apply   'README.md',
  git-diff-apply   'addon',
  git-diff-apply   'app',
  git-diff-apply   'bower.json',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'index.js',
  git-diff-apply   'package.json',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply git add -A +35ms
  git-diff-apply  +15ms
  git-diff-apply git commit -m "startTag" +0ms
  git-diff-apply [11954e60-a215-11e7-99d9-f16f7bd616cd (root-commit) 2e5e0fc] startTag
  git-diff-apply  45 files changed, 648 insertions(+)
  git-diff-apply  create mode 100644 .DS_Store
  git-diff-apply  create mode 100644 .bowerrc
  git-diff-apply  create mode 100644 .editorconfig
  git-diff-apply  create mode 100644 .ember-cli
  git-diff-apply  create mode 100644 .gitignore
  git-diff-apply  create mode 100644 .jshintrc
  git-diff-apply  create mode 100644 .npmignore
  git-diff-apply  create mode 100644 .travis.yml
  git-diff-apply  create mode 100644 .watchmanconfig
  git-diff-apply  create mode 100644 LICENSE.md
  git-diff-apply  create mode 100644 README.md
  git-diff-apply  create mode 100644 addon/.gitkeep
  git-diff-apply  create mode 100644 app/.gitkeep
  git-diff-apply  create mode 100644 bower.json
  git-diff-apply  create mode 100644 config/ember-try.js
  git-diff-apply  create mode 100644 config/environment.js
  git-diff-apply  create mode 100644 ember-cli-build.js
  git-diff-apply  create mode 100644 index.js
  git-diff-apply  create mode 100644 package.json
  git-diff-apply  create mode 100644 testem.js
  git-diff-apply  create mode 100644 tests/.jshintrc
  git-diff-apply  create mode 100644 tests/dummy/app/app.js
  git-diff-apply  create mode 100644 tests/dummy/app/components/.gitkeep
  git-diff-apply  create mode 100644 tests/dummy/app/controllers/.gitkeep
  git-diff-apply  create mode 100644 tests/dummy/app/helpers/.gitkeep
  git-diff-apply  create mode 100644 tests/dummy/app/index.html
  git-diff-apply  create mode 100644 tests/dummy/app/models/.gitkeep
  git-diff-apply  create mode 100644 tests/dummy/app/resolver.js
  git-diff-apply  create mode 100644 tests/dummy/app/router.js
  git-diff-apply  create mode 100644 tests/dummy/app/routes/.gitkeep
  git-diff-apply  create mode 100644 tests/dummy/app/styles/app.css
  git-diff-apply  create mode 100644 tests/dummy/app/templates/application.hbs
  git-diff-apply  create mode 100644 tests/dummy/app/templates/components/.gitkeep
  git-diff-apply  create mode 100644 tests/dummy/config/environment.js
  git-diff-apply  create mode 100644 tests/dummy/public/crossdomain.xml
  git-diff-apply  create mode 100644 tests/dummy/public/robots.txt
  git-diff-apply  create mode 100644 tests/helpers/destroy-app.js
  git-diff-apply  create mode 100644 tests/helpers/module-for-acceptance.js
  git-diff-apply  create mode 100644 tests/helpers/resolver.js
  git-diff-apply  create mode 100644 tests/helpers/start-app.js
  git-diff-apply  create mode 100644 tests/index.html
  git-diff-apply  create mode 100644 tests/integration/.gitkeep
  git-diff-apply  create mode 100644 tests/test-helper.js
  git-diff-apply  create mode 100644 tests/unit/.gitkeep
  git-diff-apply  create mode 100644 vendor/.gitkeep
  git-diff-apply  +22ms
  git-diff-apply git --git-dir="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git" diff v2.11.1 v2.12.3 | git apply +4ms
  git-diff-apply  +17ms
  git-diff-apply git checkout -- package.json +0ms
  git-diff-apply  +13ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  D .jshintrc
  git-diff-apply  M .npmignore
  git-diff-apply  M .travis.yml
  git-diff-apply  M config/ember-try.js
  git-diff-apply  M config/environment.js
  git-diff-apply  M ember-cli-build.js
  git-diff-apply  M index.js
  git-diff-apply  M testem.js
  git-diff-apply  D tests/.jshintrc
  git-diff-apply  M tests/dummy/config/environment.js
  git-diff-apply  M tests/helpers/start-app.js
  git-diff-apply ?? .eslintrc.js
  git-diff-apply ?? tests/.eslintrc.js
  git-diff-apply  +12ms
  git-diff-apply git add -A +0ms
  git-diff-apply  +14ms
  git-diff-apply git commit -m "diff" +0ms
  git-diff-apply [11954e60-a215-11e7-99d9-f16f7bd616cd 69a5804] diff
  git-diff-apply  13 files changed, 30 insertions(+), 101 deletions(-)
  git-diff-apply  create mode 100644 .eslintrc.js
  git-diff-apply  delete mode 100644 .jshintrc
  git-diff-apply  create mode 100644 tests/.eslintrc.js
  git-diff-apply  delete mode 100644 tests/.jshintrc
  git-diff-apply  +16ms
  git-diff-apply git rev-parse HEAD +1ms
  git-diff-apply 69a58048c2f77816e9ee4a5335b47d9d9ee2d9f8
  git-diff-apply  +11ms
  git-diff-apply git checkout 3181-test +0ms
Switched to branch '3181-test'
  git-diff-apply  +136ms
  git-diff-apply git cherry-pick --no-commit 69a58048c2f77816e9ee4a5335b47d9d9ee2d9f8 +0ms
error: could not apply 69a5804... diff
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
Resolved '.npmignore' using previous resolution.
Resolved '.travis.yml' using previous resolution.
Resolved 'config/ember-try.js' using previous resolution.
Resolved 'config/environment.js' using previous resolution.
Resolved 'ember-cli-build.js' using previous resolution.
Recorded preimage for 'testem.json'
Resolved 'tests/helpers/start-app.js' using previous resolution.
  git-diff-apply git branch -D 11954e60-a215-11e7-99d9-f16f7bd616cd +81ms
  git-diff-apply Deleted branch 11954e60-a215-11e7-99d9-f16f7bd616cd (was 69a5804).
  git-diff-apply  +11ms
  git-diff-apply git mergetool +388ms

This message is displayed because 'merge.tool' is not configured.
See 'git mergetool --tool-help' or 'git help config' for more details.
'git mergetool' will now attempt to use one of the following tools:
tortoisemerge emerge vimdiff
Merging:
.jshintrc
testem.json
tests/.jshintrc

Deleted merge conflict for '.jshintrc':
  {local}: modified file
  {remote}: deleted
Use (m)odified or (d)eleted file, or (a)bort? m

Normal merge conflict for 'testem.json':
  {local}: modified file
  {remote}: modified file
Hit return to start merge resolution tool (vimdiff): 
4 files to edit

Deleted merge conflict for 'tests/.jshintrc':
  {local}: modified file
  {remote}: deleted
Use (m)odified or (d)eleted file, or (a)bort? m
  git-diff-apply git --git-dir="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git" rev-parse v2.12.3 +31s
  git-diff-apply d26802a39339b024e8bb9ecd76ac315bd3dd46e2
  git-diff-apply  +16ms
  git-diff-apply git --git-dir="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN/.git" --work-tree="/var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T/tmp-5564t4aPqd2QzQsN" checkout d26802a39339b024e8bb9ecd76ac315bd3dd46e2 +0ms
Previous HEAD position was 4baef6c... 2.11.1
HEAD is now at d26802a... 2.12.3
  git-diff-apply  +21ms
TypeError: Invalid comparator: ember-cli/loader.js
    at Comparator.parse (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:662:8)
    at /Users/alex/.config/yarn/global/node_modules/semver/semver.js:828:12
    at Array.map (native)
    at Range.parseRange (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:827:13)
    at Range.<anonymous> (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:769:17)
    at Array.map (native)
    at new Range (/Users/alex/.config/yarn/global/node_modules/semver/semver.js:768:40)
    at minVersion (/Users/alex/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:14:11)
    at /Users/alex/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:57:19

```

**Comment by kellyselden** [comment]
It looks like a version string in your package.json was unexpected. Can you paste in all the dependencies, devDependencies, etc., or just paste in your entire package.json?

**Comment by alexmiddeleer** [comment]
Sure - thanks for taking a look. I changed name, description and repo but otherwise this is verbatim
```
{
  "name": "foo",
  "version": "0.1.0",
  "description": "foo",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember try:testall"
  },
  "repository": "https://github.com/foo/bar",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "active-model-adapter": "2.1.1",
    "bower": "^1.4.1",
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.11.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-mirage": "^0.2.3",
    "ember-cli-qunit": "1.3.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-concurrency": "0.7.8",
    "ember-cp-validations": "2.9.8",
    "ember-data": "2.11.0",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-i18n": "4.2.2",
    "ember-i18n-cp-validations": "3.0.2",
    "ember-inflector": "1.9.6",
    "ember-inline-svg": "0.1.5",
    "ember-lazy-video": "git://github.com/raymondjcox/ember-lazy-video#d4b0372",
    "ember-network": "0.3.0",
    "ember-sinon": "0.2.1",
    "ember-source": "~2.11.0",
    "ember-suave": "1.2.3",
    "ember-truth-helpers": "1.1.0",
    "ember-try": "0.0.6",
    "ember-watson": "0.7.0",
    "loader.js": "ember-cli/loader.js",
    "numeral": "^1.5.3",
    "phantomjs": "1.9.18"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "broccoli-funnel": "^1.0.1",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-js-cookie": "0.1.1"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```

**Comment by alexmiddeleer** [comment]
I wonder if it is the loader.js version that is causing the issue...

**Comment by alexmiddeleer** [comment]
Ah yes, that was it. Thanks! Not sure why that got into the package.json in the first place, to be honest.

**Comment by kellyselden** [comment]
Cool. Not sure why it broke under that condition yet. It should have "just worked".

**Comment by kellyselden** [comment]
Closing for now. Might not be an issue anymore with the package.json improvements.
