### ISSUE TITLE
NPM Auth issue

### ISSUE THREAD

**Issue by medokin** [kellyselden/ember-cli-update#153]
We are using http://inedo.com/proget as npm proxy, maybe thats the problem?

```
  ember-cli-update npm info ember-cli versions --json +0ms
npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nj.ALPHA\AppData\Roaming\npm-cache\_logs\2017-10-11T07_41_47_926Z-debug.log
child_process.js:524
    throw err;
    ^

Error: Command failed: npm info ember-cli versions --json
npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nj.ALPHA\AppData\Roaming\npm-cache\_logs\2017-10-11T07_41_47_926Z-debug.log

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at run (C:\Users\nj.ALPHA\AppData\Roaming\npm\node_modules\ember-cli-update\src\run.js:8:19)
    at emberCliUpdate (C:\Users\nj.ALPHA\AppData\Roaming\npm\node_modules\ember-cli-update\src\index.js:30:5)
    at Object.<anonymous> (C:\Users\nj.ALPHA\AppData\Roaming\npm\node_modules\ember-cli-update\bin\ember-cli-update.js:15:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by medokin** [comment]
Nevermind, logging in fixed the problem.
