### ISSUE TITLE
TypeError: Invalid comparator

### ISSUE THREAD

**Issue by Turbo87** [kellyselden/ember-cli-update#235]
Our `package.json` currently contains `"ember-data": "pangratz/data#fix_links"` which seems to crash `ember-cli-update`:

```
TypeError: Invalid comparator: pangratz/data#fix_links
    at Comparator.parse (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:662:8)
    at /Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:828:12
    at Array.map (<anonymous>)
    at Range.parseRange (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:827:13)
    at Range.<anonymous> (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:769:17)
    at Array.map (<anonymous>)
    at new Range (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:768:40)
    at minVersion (/Users/tbieniek/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:14:11)
    at /Users/tbieniek/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:57:19
```

DEBUG output:

```
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
  ember-cli-update   "0.0.1",
  ember-cli-update   "0.0.2",
  ember-cli-update   "0.0.3",
  ember-cli-update   "0.0.4",
  ember-cli-update   "0.0.5",
  ember-cli-update   "0.0.6",
  ember-cli-update   "0.0.7",
  ember-cli-update   "0.0.8",
  ember-cli-update   "0.0.9",
  ember-cli-update   "0.0.10",
  ember-cli-update   "0.0.11",
  ember-cli-update   "0.0.12",
  ember-cli-update   "0.0.13",
  ember-cli-update   "0.0.14",
  ember-cli-update   "0.0.15",
  ember-cli-update   "0.0.16",
  ember-cli-update   "0.0.18",
  ember-cli-update   "0.0.19",
  ember-cli-update   "0.0.20",
  ember-cli-update   "0.0.21",
  ember-cli-update   "0.0.22",
  ember-cli-update   "0.0.23",
  ember-cli-update   "0.0.24",
  ember-cli-update   "0.0.25",
  ember-cli-update   "0.0.27",
  ember-cli-update   "0.0.28",
  ember-cli-update   "0.0.29",
  ember-cli-update   "0.0.32",
  ember-cli-update   "0.0.33",
  ember-cli-update   "0.0.34",
  ember-cli-update   "0.0.35",
  ember-cli-update   "0.0.36",
  ember-cli-update   "0.0.37",
  ember-cli-update   "0.0.38",
  ember-cli-update   "0.0.39",
  ember-cli-update   "0.0.40",
  ember-cli-update   "0.0.41",
  ember-cli-update   "0.0.42",
  ember-cli-update   "0.0.43",
  ember-cli-update   "0.0.44",
  ember-cli-update   "0.0.45",
  ember-cli-update   "0.0.46",
  ember-cli-update   "0.0.47",
  ember-cli-update   "0.1.0",
  ember-cli-update   "0.1.1",
  ember-cli-update   "0.1.2",
  ember-cli-update   "0.1.3",
  ember-cli-update   "0.1.4",
  ember-cli-update   "0.1.5",
  ember-cli-update   "0.1.6",
  ember-cli-update   "0.1.7",
  ember-cli-update   "0.1.8",
  ember-cli-update   "0.1.9",
  ember-cli-update   "0.1.10",
  ember-cli-update   "0.1.11",
  ember-cli-update   "0.1.12",
  ember-cli-update   "0.1.13",
  ember-cli-update   "0.1.14",
  ember-cli-update   "0.1.15",
  ember-cli-update   "0.2.0-beta.1",
  ember-cli-update   "0.2.0",
  ember-cli-update   "0.2.1",
  ember-cli-update   "0.2.2",
  ember-cli-update   "0.2.3",
  ember-cli-update   "0.2.4",
  ember-cli-update   "0.2.5",
  ember-cli-update   "0.2.6",
  ember-cli-update   "0.2.7",
  ember-cli-update   "1.13.0",
  ember-cli-update   "1.13.1",
  ember-cli-update   "1.13.5",
  ember-cli-update   "1.13.6",
  ember-cli-update   "1.13.7",
  ember-cli-update   "1.13.8",
  ember-cli-update   "1.13.9",
  ember-cli-update   "1.13.10",
  ember-cli-update   "1.13.11",
  ember-cli-update   "1.13.12",
  ember-cli-update   "1.13.13",
  ember-cli-update   "1.13.14",
  ember-cli-update   "1.13.15",
  ember-cli-update   "2.2.0-beta.1",
  ember-cli-update   "2.2.0-beta.2",
  ember-cli-update   "2.2.0-beta.3",
  ember-cli-update   "2.2.0-beta.4",
  ember-cli-update   "2.2.0-beta.5",
  ember-cli-update   "2.2.0-beta.6",
  ember-cli-update   "2.3.0-beta.1",
  ember-cli-update   "2.3.0-beta.2",
  ember-cli-update   "2.3.0",
  ember-cli-update   "2.4.0",
  ember-cli-update   "2.4.1",
  ember-cli-update   "2.4.2",
  ember-cli-update   "2.4.3",
  ember-cli-update   "2.5.0",
  ember-cli-update   "2.5.1",
  ember-cli-update   "2.6.0-beta.1",
  ember-cli-update   "2.6.0-beta.2",
  ember-cli-update   "2.6.0-beta.3",
  ember-cli-update   "2.6.0",
  ember-cli-update   "2.6.1",
  ember-cli-update   "2.6.2",
  ember-cli-update   "2.6.3",
  ember-cli-update   "2.7.0-beta.1",
  ember-cli-update   "2.7.0-beta.2",
  ember-cli-update   "2.7.0-beta.3",
  ember-cli-update   "2.7.0-beta.4",
  ember-cli-update   "2.7.0-beta.5",
  ember-cli-update   "2.7.0-beta.6",
  ember-cli-update   "2.7.0",
  ember-cli-update   "2.8.0-beta.1",
  ember-cli-update   "2.8.0-beta.2",
  ember-cli-update   "2.8.0-beta.3",
  ember-cli-update   "2.8.0",
  ember-cli-update   "2.9.0-beta.1",
  ember-cli-update   "2.9.0-beta.2",
  ember-cli-update   "2.9.0",
  ember-cli-update   "2.9.1",
  ember-cli-update   "2.10.0-beta.1",
  ember-cli-update   "2.10.0-beta.2",
  ember-cli-update   "2.10.0",
  ember-cli-update   "2.10.1",
  ember-cli-update   "2.11.0-beta.1",
  ember-cli-update   "2.11.0-beta.2",
  ember-cli-update   "2.11.0",
  ember-cli-update   "2.11.1",
  ember-cli-update   "2.12.0-beta.1",
  ember-cli-update   "2.12.0-beta.2",
  ember-cli-update   "2.12.0",
  ember-cli-update   "2.12.1",
  ember-cli-update   "2.12.2",
  ember-cli-update   "2.12.3",
  ember-cli-update   "2.13.0-beta.1",
  ember-cli-update   "2.13.0-beta.2",
  ember-cli-update   "2.13.0-beta.3",
  ember-cli-update   "2.13.0-beta.4",
  ember-cli-update   "2.13.0",
  ember-cli-update   "2.13.1",
  ember-cli-update   "2.13.2",
  ember-cli-update   "2.13.3",
  ember-cli-update   "2.14.0-beta.1",
  ember-cli-update   "2.14.0-beta.2",
  ember-cli-update   "2.14.0",
  ember-cli-update   "2.14.1",
  ember-cli-update   "2.14.2",
  ember-cli-update   "2.15.0-beta.1",
  ember-cli-update   "2.15.0-beta.2",
  ember-cli-update   "2.15.0",
  ember-cli-update   "2.15.1",
  ember-cli-update   "2.16.0-beta.1",
  ember-cli-update   "2.16.0-beta.2",
  ember-cli-update   "2.16.0",
  ember-cli-update   "2.16.1",
  ember-cli-update   "2.16.2",
  ember-cli-update   "2.17.0-beta.1",
  ember-cli-update   "2.17.0-beta.2",
  ember-cli-update   "2.17.0",
  ember-cli-update   "2.17.1",
  ember-cli-update   "2.18.0-beta.1"
  ember-cli-update ]
  ember-cli-update  +763ms
  ember-cli-update npm info ember-cli@latest version --json +7ms
  ember-cli-update "2.17.1"
  ember-cli-update  +463ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  +27ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output /var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git +1ms
Cloning into bare repository '/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git'...
  git-diff-apply  +2s
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" rev-parse v2.16.2 +0ms
  git-diff-apply 80789a62365aedf13cb8c969cb9c020b67333967
  git-diff-apply  +9ms
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" --work-tree="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70" checkout 80789a62365aedf13cb8c969cb9c020b67333967 +0ms
Note: checking out '80789a62365aedf13cb8c969cb9c020b67333967'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 80789a6... 2.16.2
  git-diff-apply  +24ms
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" rev-parse v2.17.1 +3ms
  git-diff-apply 90ade7c5cbb928d4d2a688c20bfedb5bb135ff15
  git-diff-apply  +10ms
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" --work-tree="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70" checkout 90ade7c5cbb928d4d2a688c20bfedb5bb135ff15 +0ms
Previous HEAD position was 80789a6... 2.16.2
HEAD is now at 90ade7c... 2.17.1
  git-diff-apply  +20ms
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" rev-parse v2.16.2 +1ms
  git-diff-apply 80789a62365aedf13cb8c969cb9c020b67333967
  git-diff-apply  +15ms
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" --work-tree="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70" checkout 80789a62365aedf13cb8c969cb9c020b67333967 +0ms
Previous HEAD position was 90ade7c... 2.17.1
HEAD is now at 80789a6... 2.16.2
  git-diff-apply  +18ms
  git-diff-apply git symbolic-ref --short HEAD +0ms
  git-diff-apply cli
  git-diff-apply  +11ms
  git-diff-apply git checkout --orphan 03378580-df1f-11e7-9ccb-a9e58586842a +0ms
Switched to a new branch '03378580-df1f-11e7-9ccb-a9e58586842a'
  git-diff-apply  +43ms
  git-diff-apply git reset --hard +0ms
  git-diff-apply  +306ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'README.md',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply copy /var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70 /Users/tbieniek/Code/trainline/webapp +2ms
  git-diff-apply git add -A +18ms
  git-diff-apply  +20ms
  git-diff-apply git commit -m "message" +1ms
  git-diff-apply [03378580-df1f-11e7-9ccb-a9e58586842a (root-commit) 103b7efa3] message
  git-diff-apply  36 files changed, 468 insertions(+)
  git-diff-apply  create mode 100644 .editorconfig
  git-diff-apply  create mode 100644 .ember-cli
  git-diff-apply  create mode 100644 .eslintrc.js
  git-diff-apply  create mode 100644 .gitignore
  git-diff-apply  create mode 100644 .travis.yml
  git-diff-apply  create mode 100644 .watchmanconfig
  git-diff-apply  create mode 100644 README.md
  git-diff-apply  create mode 100644 app/app.js
  git-diff-apply  create mode 100644 app/components/.gitkeep
  git-diff-apply  create mode 100644 app/controllers/.gitkeep
  git-diff-apply  create mode 100644 app/helpers/.gitkeep
  git-diff-apply  create mode 100644 app/index.html
  git-diff-apply  create mode 100644 app/models/.gitkeep
  git-diff-apply  create mode 100644 app/resolver.js
  git-diff-apply  create mode 100644 app/router.js
  git-diff-apply  create mode 100644 app/routes/.gitkeep
  git-diff-apply  create mode 100644 app/styles/app.css
  git-diff-apply  create mode 100644 app/templates/application.hbs
  git-diff-apply  create mode 100644 app/templates/components/.gitkeep
  git-diff-apply  create mode 100644 config/environment.js
  git-diff-apply  create mode 100644 config/targets.js
  git-diff-apply  create mode 100644 ember-cli-build.js
  git-diff-apply  create mode 100644 package.json
  git-diff-apply  create mode 100644 public/crossdomain.xml
  git-diff-apply  create mode 100644 public/robots.txt
  git-diff-apply  create mode 100644 testem.js
  git-diff-apply  create mode 100644 tests/.eslintrc.js
  git-diff-apply  create mode 100644 tests/helpers/destroy-app.js
  git-diff-apply  create mode 100644 tests/helpers/module-for-acceptance.js
  git-diff-apply  create mode 100644 tests/helpers/resolver.js
  git-diff-apply  create mode 100644 tests/helpers/start-app.js
  git-diff-apply  create mode 100644 tests/index.html
  git-diff-apply  create mode 100644 tests/integration/.gitkeep
  git-diff-apply  create mode 100644 tests/test-helper.js
  git-diff-apply  create mode 100644 tests/unit/.gitkeep
  git-diff-apply  create mode 100644 vendor/.gitkeep
  git-diff-apply  +25ms
  git-diff-apply git --git-dir="/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/tmp-74145d6HI24mL9C70/.git" diff v2.16.2 v2.17.1 | git apply +0ms
  git-diff-apply  +39ms
  git-diff-apply git checkout -- package.json +0ms
  git-diff-apply  +33ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  M README.md
  git-diff-apply  M testem.js
  git-diff-apply  D tests/helpers/resolver.js
  git-diff-apply  M tests/test-helper.js
  git-diff-apply  +18ms
  git-diff-apply git add -A +0ms
  git-diff-apply  +17ms
  git-diff-apply git commit -m "message" +0ms
  git-diff-apply [03378580-df1f-11e7-9ccb-a9e58586842a be114587b] message
  git-diff-apply  4 files changed, 8 insertions(+), 20 deletions(-)
  git-diff-apply  delete mode 100644 tests/helpers/resolver.js
  git-diff-apply  +26ms
  git-diff-apply git rev-parse HEAD +0ms
  git-diff-apply be114587b7b508b073febd503cc18361655d7129
  git-diff-apply  +11ms
  git-diff-apply git checkout cli +0ms
Switched to branch 'cli'
  git-diff-apply  +708ms
  git-diff-apply git cherry-pick --no-commit be114587b7b508b073febd503cc18361655d7129 +1ms
error: could not apply be114587b... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
  git-diff-apply git branch -D 03378580-df1f-11e7-9ccb-a9e58586842a +767ms
  git-diff-apply Deleted branch 03378580-df1f-11e7-9ccb-a9e58586842a (was be114587b).
  git-diff-apply  +17ms
TypeError: Invalid comparator: pangratz/data#fix_links
    at Comparator.parse (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:662:8)
    at /Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:828:12
    at Array.map (<anonymous>)
    at Range.parseRange (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:827:13)
    at Range.<anonymous> (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:769:17)
    at Array.map (<anonymous>)
    at new Range (/Users/tbieniek/.config/yarn/global/node_modules/semver/semver.js:768:40)
    at minVersion (/Users/tbieniek/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:14:11)
    at /Users/tbieniek/.config/yarn/global/node_modules/three-way-merger/lib/merge.js:57:19
```

**Comment by kellyselden** [comment]
If you've got the time, a failing test or a fix to https://github.com/kellyselden/merge-package.json would be awesome.

**Comment by Turbo87** [comment]
Since https://github.com/bantic/three-way-merger/pull/23 was merged I'm assuming this can be closed now 🤔
