### ISSUE TITLE
Error - fatal: ambiguous argument 'v2.18.1'

### ISSUE THREAD

**Issue by eriktrom** [kellyselden/ember-cli-update#252]
Installing ember-cli-update via `ember install ember-cli-update`, then running `ember update` in an older app, with node_modules already installed, using node version 7.x, spit out the following error. It also installed the following 2 additional packages which seem erroneous:

Environment at time of output:

`ember -v`:

> ember-cli: 2.15.1
> node: 7.10.0
> os: darwin x64

`yarn -v`:

> 1.3.2

`node -v`:

> v7.10.0

- Bug 1: package.json contains these packages, which seems very odd:

```
"ember": "^1.0.3",
"install": "^0.10.4"
```

- Bug 2:  Error upon running `ember update`

Output from `DEBUG=ember-cli-update,git-diff-apply ember update`

```
Cloning into bare repository '/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-599505AD9Kp6FoGrY/.git'...
Note: checking out '36bc50b2ed21fd81933fe5f65968564ced999318'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 36bc50b... 2.14.2
fatal: ambiguous argument 'v2.18.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
File: /bin/sh
Command failed: git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-599505AD9Kp6FoGrY/.git" rev-parse v2.18.1
fatal: ambiguous argument 'v2.18.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Error: Command failed: git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-599505AD9Kp6FoGrY/.git" rev-parse v2.18.1
fatal: ambiguous argument 'v2.18.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at run (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/run.js:8:19)
    at checkOutTag (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/check-out-tag.js:9:13)
    at buildReturnObject (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/index.js:69:5)
    at Promise.resolve.then (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/index.js:148:20)
    at process._tickCallback (internal/process/next_tick.js:109:7)
trom:~/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web ± (master ✓)
DEBUG=ember-cli-update,git-diff-apply ember update
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
  ember-cli-update   "0.0.1",
  ember-cli-update   "0.0.2",
  ember-cli-update   "0.0.3",
  ember-cli-update   "0.0.4",
  ember-cli-update   "0.0.5",
  ember-cli-update   "0.0.6",
  ember-cli-update   "0.0.7",
  ember-cli-update   "0.0.8",
  ember-cli-update   "0.0.9",
  ember-cli-update   "0.0.10",
  ember-cli-update   "0.0.11",
  ember-cli-update   "0.0.12",
  ember-cli-update   "0.0.13",
  ember-cli-update   "0.0.14",
  ember-cli-update   "0.0.15",
  ember-cli-update   "0.0.16",
  ember-cli-update   "0.0.18",
  ember-cli-update   "0.0.19",
  ember-cli-update   "0.0.20",
  ember-cli-update   "0.0.21",
  ember-cli-update   "0.0.22",
  ember-cli-update   "0.0.23",
  ember-cli-update   "0.0.24",
  ember-cli-update   "0.0.25",
  ember-cli-update   "0.0.27",
  ember-cli-update   "0.0.28",
  ember-cli-update   "0.0.29",
  ember-cli-update   "0.0.32",
  ember-cli-update   "0.0.33",
  ember-cli-update   "0.0.34",
  ember-cli-update   "0.0.35",
  ember-cli-update   "0.0.36",
  ember-cli-update   "0.0.37",
  ember-cli-update   "0.0.38",
  ember-cli-update   "0.0.39",
  ember-cli-update   "0.0.40",
  ember-cli-update   "0.0.41",
  ember-cli-update   "0.0.42",
  ember-cli-update   "0.0.43",
  ember-cli-update   "0.0.44",
  ember-cli-update   "0.0.45",
  ember-cli-update   "0.0.46",
  ember-cli-update   "0.0.47",
  ember-cli-update   "0.1.0",
  ember-cli-update   "0.1.1",
  ember-cli-update   "0.1.2",
  ember-cli-update   "0.1.3",
  ember-cli-update   "0.1.4",
  ember-cli-update   "0.1.5",
  ember-cli-update   "0.1.6",
  ember-cli-update   "0.1.7",
  ember-cli-update   "0.1.8",
  ember-cli-update   "0.1.9",
  ember-cli-update   "0.1.10",
  ember-cli-update   "0.1.11",
  ember-cli-update   "0.1.12",
  ember-cli-update   "0.1.13",
  ember-cli-update   "0.1.14",
  ember-cli-update   "0.1.15",
  ember-cli-update   "0.2.0-beta.1",
  ember-cli-update   "0.2.0",
  ember-cli-update   "0.2.1",
  ember-cli-update   "0.2.2",
  ember-cli-update   "0.2.3",
  ember-cli-update   "0.2.4",
  ember-cli-update   "0.2.5",
  ember-cli-update   "0.2.6",
  ember-cli-update   "0.2.7",
  ember-cli-update   "1.13.0",
  ember-cli-update   "1.13.1",
  ember-cli-update   "1.13.5",
  ember-cli-update   "1.13.6",
  ember-cli-update   "1.13.7",
  ember-cli-update   "1.13.8",
  ember-cli-update   "1.13.9",
  ember-cli-update   "1.13.10",
  ember-cli-update   "1.13.11",
  ember-cli-update   "1.13.12",
  ember-cli-update   "1.13.13",
  ember-cli-update   "1.13.14",
  ember-cli-update   "1.13.15",
  ember-cli-update   "2.2.0-beta.1",
  ember-cli-update   "2.2.0-beta.2",
  ember-cli-update   "2.2.0-beta.3",
  ember-cli-update   "2.2.0-beta.4",
  ember-cli-update   "2.2.0-beta.5",
  ember-cli-update   "2.2.0-beta.6",
  ember-cli-update   "2.3.0-beta.1",
  ember-cli-update   "2.3.0-beta.2",
  ember-cli-update   "2.3.0",
  ember-cli-update   "2.4.0",
  ember-cli-update   "2.4.1",
  ember-cli-update   "2.4.2",
  ember-cli-update   "2.4.3",
  ember-cli-update   "2.5.0",
  ember-cli-update   "2.5.1",
  ember-cli-update   "2.6.0-beta.1",
  ember-cli-update   "2.6.0-beta.2",
  ember-cli-update   "2.6.0-beta.3",
  ember-cli-update   "2.6.0",
  ember-cli-update   "2.6.1",
  ember-cli-update   "2.6.2",
  ember-cli-update   "2.6.3",
  ember-cli-update   "2.7.0-beta.1",
  ember-cli-update   "2.7.0-beta.2",
  ember-cli-update   "2.7.0-beta.3",
  ember-cli-update   "2.7.0-beta.4",
  ember-cli-update   "2.7.0-beta.5",
  ember-cli-update   "2.7.0-beta.6",
  ember-cli-update   "2.7.0",
  ember-cli-update   "2.8.0-beta.1",
  ember-cli-update   "2.8.0-beta.2",
  ember-cli-update   "2.8.0-beta.3",
  ember-cli-update   "2.8.0",
  ember-cli-update   "2.9.0-beta.1",
  ember-cli-update   "2.9.0-beta.2",
  ember-cli-update   "2.9.0",
  ember-cli-update   "2.9.1",
  ember-cli-update   "2.10.0-beta.1",
  ember-cli-update   "2.10.0-beta.2",
  ember-cli-update   "2.10.0",
  ember-cli-update   "2.10.1",
  ember-cli-update   "2.11.0-beta.1",
  ember-cli-update   "2.11.0-beta.2",
  ember-cli-update   "2.11.0",
  ember-cli-update   "2.11.1",
  ember-cli-update   "2.12.0-beta.1",
  ember-cli-update   "2.12.0-beta.2",
  ember-cli-update   "2.12.0",
  ember-cli-update   "2.12.1",
  ember-cli-update   "2.12.2",
  ember-cli-update   "2.12.3",
  ember-cli-update   "2.13.0-beta.1",
  ember-cli-update   "2.13.0-beta.2",
  ember-cli-update   "2.13.0-beta.3",
  ember-cli-update   "2.13.0-beta.4",
  ember-cli-update   "2.13.0",
  ember-cli-update   "2.13.1",
  ember-cli-update   "2.13.2",
  ember-cli-update   "2.13.3",
  ember-cli-update   "2.14.0-beta.1",
  ember-cli-update   "2.14.0-beta.2",
  ember-cli-update   "2.14.0",
  ember-cli-update   "2.14.1",
  ember-cli-update   "2.14.2",
  ember-cli-update   "2.15.0-beta.1",
  ember-cli-update   "2.15.0-beta.2",
  ember-cli-update   "2.15.0",
  ember-cli-update   "2.15.1",
  ember-cli-update   "2.16.0-beta.1",
  ember-cli-update   "2.16.0-beta.2",
  ember-cli-update   "2.16.0",
  ember-cli-update   "2.16.1",
  ember-cli-update   "2.16.2",
  ember-cli-update   "2.17.0-beta.1",
  ember-cli-update   "2.17.0-beta.2",
  ember-cli-update   "2.17.0",
  ember-cli-update   "2.17.1",
  ember-cli-update   "2.17.2",
  ember-cli-update   "2.18.0-beta.1",
  ember-cli-update   "2.18.0-beta.2",
  ember-cli-update   "2.18.0",
  ember-cli-update   "2.18.1",
  ember-cli-update   "3.0.0-beta.1",
  ember-cli-update   "3.0.0-beta.2"
  ember-cli-update ]
  ember-cli-update  +771ms
  ember-cli-update npm info ember-cli@latest version --json +11ms
  ember-cli-update "2.18.1"
  ember-cli-update  +470ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  +22ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output /var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git +1ms
Cloning into bare repository '/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git'...
  git-diff-apply  +285ms
  git-diff-apply git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git" rev-parse v2.14.2 +0ms
  git-diff-apply 36bc50b2ed21fd81933fe5f65968564ced999318
  git-diff-apply  +9ms
  git-diff-apply git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git" --work-tree="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg" checkout 36bc50b2ed21fd81933fe5f65968564ced999318 +0ms
Note: checking out '36bc50b2ed21fd81933fe5f65968564ced999318'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 36bc50b... 2.14.2
  git-diff-apply  +18ms
  git-diff-apply git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git" rev-parse v2.18.1 +2ms
fatal: ambiguous argument 'v2.18.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
File: /bin/sh
Command failed: git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git" rev-parse v2.18.1
fatal: ambiguous argument 'v2.18.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Error: Command failed: git --git-dir="/var/folders/85/m6931n7s26l_48j9g9lrn7zh0000gn/T/tmp-60983YRCmYowArQjg/.git" rev-parse v2.18.1
fatal: ambiguous argument 'v2.18.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at run (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/run.js:8:19)
    at checkOutTag (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/check-out-tag.js:9:13)
    at buildReturnObject (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/index.js:69:5)
    at Promise.resolve.then (/Users/trom/Documents/desktop_space/Dropbox/dev/eriktrom/craft/craft-app-manager/build/app-web/node_modules/git-diff-apply/src/index.js:148:20)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by eriktrom** [comment]
duplicate of https://github.com/kellyselden/ember-cli-update/issues/248 closing
